# Copyright 2018 Red Hat, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Tasks to deploy AWS ec2 instance(s) based in the requested parameters
---

- name: "Create ec2 instance(s)"
  ec2:
    image: "{{ ec2_image }}"
    instance_type: "{{ ec2_instance_type }}"
    group: "{{ ec2_group }}"
    termination_protection: "{{ aws_termination_protection }}"
    key_name: "{{ aws_key_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    exact_count: 1
    wait: yes
    count_tag:
      Name: "{{ ec2_name }}-{{ item }}"
    instance_tags:
      "{{ ec2_instance_tags|combine({ 'Name': ec2_name + '-' + item,
                                      'kubernetes.io/cluster/cluster-' + env_id: env_id } ) }}"
    volumes: "{{ ec2_volumes }}"
  with_sequence:
    count="{{ ec2_num_instances }}"
  register: ec2_instances
