# Copyright 2018 Red Hat, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Validate OpenShift Token Provided
  fail: msg="OpenShift Token Not Provided"
  failed_when: (openshift_token is undefined) or (openshift_token is none) or (openshift_token|trim == '')
  tags: always

- name: Set Facts
  set_fact: kubeconfig="/tmp/openshift-management-{{ ansible_date_time.epoch }}/config"
  tags: always

- name: Create Directory
  file: path="{{ kubeconfig | dirname }}" state=directory
  notify: cleanup openshift login
  tags: always

- name: Login to OpenShift
  shell: oc login --token={{ openshift_token }} {{ openshift_login_insecure_flag }} {{ openshift_master_url }} 
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tags: always

- import_tasks: prune-builds.yml
  when: "{{ openshift_prune_builds | default(False) }}"
  tags: openshift-management-builds

- import_tasks: prune-deployments.yml
  when: "{{ openshift_prune_deployments | default(False) }}"
  tags: openshift-management-deployments

- import_tasks: prune-images.yml
  when: "{{ openshift_prune_images | default(False) }}"
  tags: openshift-management-images

- import_tasks: prune-projects.yml
  when: "{{ openshift_prune_projects | default(False) }}"
  tags: openshift-management-projects

